# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: x64
  buildConfiguration: 'Release'

steps:
  - script: |
      for /f "usebackq tokens=*" %l in (`"c:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -property installationPath`) do set bar=%l
      call "%bar%"\Common7\Tools\VsDevCmd.bat -arch=$(BuildPlatform)
      copy config\win32 config.h
      nmake -f win32\makefile.win32 
  displayName: Build

