# vim: se expandtab ts=4 sw=2 ai

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: x64
  buildConfiguration: 'Release'

steps:
  - script: |
      for /f "usebackq tokens=*" %%l in (`"c:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -property installationPath`) do set bar=%%l
      call "%bar%"\Common7\Tools\VsDevCmd.bat -arch=$(BuildPlatform)
      copy config\win32 config.h
      nmake -f win32\makefile.win32 
    displayName: Build

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/tcsh-x64.exe'
      artifact: 'binary'
      publishLocation: 'pipeline'